default_language_version:
  python: python3.10

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-ast
          - id: check-yaml
          - id: debug-statements
          - id: check-added-large-files
    - repo: https://github.com/sondrelg/pep585-upgrade
      rev: 'v1.0.1'
      hooks:
          - id: upgrade-type-hints
    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-new-union-types==0.4.1
                - flake8-bugbear==22.8.23
                - flake8-no-pep420==2.3.0
                - flake8-print==5.0.0
                - flake8-pep585==0.1.5.1
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.37.3
      hooks:
          - id: pyupgrade
            args: [--py310-plus]
