"""empty message

Revision ID: 636892411931
Revises: 
Create Date: 2022-11-20 17:01:19.948052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636892411931'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caso_medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('tipo_lesion', sa.String(), nullable=True),
    sa.Column('forma_lesion', sa.String(), nullable=True),
    sa.Column('especialidad', sa.String(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caso_medico_especialidad'), 'caso_medico', ['especialidad'], unique=False)
    op.create_index(op.f('ix_caso_medico_forma_lesion'), 'caso_medico', ['forma_lesion'], unique=False)
    op.create_index(op.f('ix_caso_medico_id'), 'caso_medico', ['id'], unique=False)
    op.create_index(op.f('ix_caso_medico_paciente_id'), 'caso_medico', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_caso_medico_tipo_lesion'), 'caso_medico', ['tipo_lesion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caso_medico_tipo_lesion'), table_name='caso_medico')
    op.drop_index(op.f('ix_caso_medico_paciente_id'), table_name='caso_medico')
    op.drop_index(op.f('ix_caso_medico_id'), table_name='caso_medico')
    op.drop_index(op.f('ix_caso_medico_forma_lesion'), table_name='caso_medico')
    op.drop_index(op.f('ix_caso_medico_especialidad'), table_name='caso_medico')
    op.drop_table('caso_medico')
    # ### end Alembic commands ###
